/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RotinaRouteImport } from './routes/rotina'
import { Route as EstudosRouteImport } from './routes/estudos'
import { Route as IndexRouteImport } from './routes/index'

const RotinaRoute = RotinaRouteImport.update({
  id: '/rotina',
  path: '/rotina',
  getParentRoute: () => rootRouteImport,
} as any)
const EstudosRoute = EstudosRouteImport.update({
  id: '/estudos',
  path: '/estudos',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/estudos': typeof EstudosRoute
  '/rotina': typeof RotinaRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/estudos': typeof EstudosRoute
  '/rotina': typeof RotinaRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/estudos': typeof EstudosRoute
  '/rotina': typeof RotinaRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/estudos' | '/rotina'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/estudos' | '/rotina'
  id: '__root__' | '/' | '/estudos' | '/rotina'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  EstudosRoute: typeof EstudosRoute
  RotinaRoute: typeof RotinaRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/rotina': {
      id: '/rotina'
      path: '/rotina'
      fullPath: '/rotina'
      preLoaderRoute: typeof RotinaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/estudos': {
      id: '/estudos'
      path: '/estudos'
      fullPath: '/estudos'
      preLoaderRoute: typeof EstudosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  EstudosRoute: EstudosRoute,
  RotinaRoute: RotinaRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
