/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VoceRouteImport } from './routes/voce'
import { Route as RotinaRouteImport } from './routes/rotina'
import { Route as NotificacoesRouteImport } from './routes/notificacoes'
import { Route as EstudosRouteImport } from './routes/estudos'
import { Route as CorpoRouteImport } from './routes/corpo'
import { Route as CofrinhoRouteImport } from './routes/cofrinho'
import { Route as IndexRouteImport } from './routes/index'

const VoceRoute = VoceRouteImport.update({
  id: '/voce',
  path: '/voce',
  getParentRoute: () => rootRouteImport,
} as any)
const RotinaRoute = RotinaRouteImport.update({
  id: '/rotina',
  path: '/rotina',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificacoesRoute = NotificacoesRouteImport.update({
  id: '/notificacoes',
  path: '/notificacoes',
  getParentRoute: () => rootRouteImport,
} as any)
const EstudosRoute = EstudosRouteImport.update({
  id: '/estudos',
  path: '/estudos',
  getParentRoute: () => rootRouteImport,
} as any)
const CorpoRoute = CorpoRouteImport.update({
  id: '/corpo',
  path: '/corpo',
  getParentRoute: () => rootRouteImport,
} as any)
const CofrinhoRoute = CofrinhoRouteImport.update({
  id: '/cofrinho',
  path: '/cofrinho',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/cofrinho': typeof CofrinhoRoute
  '/corpo': typeof CorpoRoute
  '/estudos': typeof EstudosRoute
  '/notificacoes': typeof NotificacoesRoute
  '/rotina': typeof RotinaRoute
  '/voce': typeof VoceRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cofrinho': typeof CofrinhoRoute
  '/corpo': typeof CorpoRoute
  '/estudos': typeof EstudosRoute
  '/notificacoes': typeof NotificacoesRoute
  '/rotina': typeof RotinaRoute
  '/voce': typeof VoceRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/cofrinho': typeof CofrinhoRoute
  '/corpo': typeof CorpoRoute
  '/estudos': typeof EstudosRoute
  '/notificacoes': typeof NotificacoesRoute
  '/rotina': typeof RotinaRoute
  '/voce': typeof VoceRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/cofrinho'
    | '/corpo'
    | '/estudos'
    | '/notificacoes'
    | '/rotina'
    | '/voce'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/cofrinho'
    | '/corpo'
    | '/estudos'
    | '/notificacoes'
    | '/rotina'
    | '/voce'
  id:
    | '__root__'
    | '/'
    | '/cofrinho'
    | '/corpo'
    | '/estudos'
    | '/notificacoes'
    | '/rotina'
    | '/voce'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CofrinhoRoute: typeof CofrinhoRoute
  CorpoRoute: typeof CorpoRoute
  EstudosRoute: typeof EstudosRoute
  NotificacoesRoute: typeof NotificacoesRoute
  RotinaRoute: typeof RotinaRoute
  VoceRoute: typeof VoceRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/voce': {
      id: '/voce'
      path: '/voce'
      fullPath: '/voce'
      preLoaderRoute: typeof VoceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rotina': {
      id: '/rotina'
      path: '/rotina'
      fullPath: '/rotina'
      preLoaderRoute: typeof RotinaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notificacoes': {
      id: '/notificacoes'
      path: '/notificacoes'
      fullPath: '/notificacoes'
      preLoaderRoute: typeof NotificacoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/estudos': {
      id: '/estudos'
      path: '/estudos'
      fullPath: '/estudos'
      preLoaderRoute: typeof EstudosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/corpo': {
      id: '/corpo'
      path: '/corpo'
      fullPath: '/corpo'
      preLoaderRoute: typeof CorpoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cofrinho': {
      id: '/cofrinho'
      path: '/cofrinho'
      fullPath: '/cofrinho'
      preLoaderRoute: typeof CofrinhoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CofrinhoRoute: CofrinhoRoute,
  CorpoRoute: CorpoRoute,
  EstudosRoute: EstudosRoute,
  NotificacoesRoute: NotificacoesRoute,
  RotinaRoute: RotinaRoute,
  VoceRoute: VoceRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
